# backend/core/multiroom/routing.py
"""
Audio routing service for Milo - UNIFIED version with SystemAudioState as single source of truth
"""
import contextlib
import logging
import asyncio
import os
import time
from typing import Any, Callable, Dict, Optional, TYPE_CHECKING
from backend.config.constants import (
    ALLOWED_FRAME_LENGTHS,
    ALLOWED_LATENCY_PROFILES,
    DEFAULT_ROC_CONFIG,
)
from backend.core.models.audio_state import AudioSource, SourceState
from backend.core.models.ws_events import (
    EqualizerEnabledChanged,
    RoutingMultiroomDisabling,
    RoutingMultiroomEnabling,
    RoutingMultiroomError,
    RoutingMultiroomReady,
    SystemStateChanged,
)
from backend.core.systemd import SystemdServiceManager  # noqa: F401 (patched in tests)
from backend.shared.background import BackgroundTaskSet
from backend.shared.decorators import handle_errors

if TYPE_CHECKING:
    from backend.core.settings import SettingsService
    from backend.core.state import AudioStateMachine


# =============================================================================
# Environment files — three independent regenerate functions, each driven
# strictly by settings.json (no class-level caches, no os.environ as truth).
#
# File ownership:
#   /var/lib/milo/routing.env     → MILO_MODE only (consumed by all sources + camilladsp)
#   /var/lib/milo/mac.env         → ROC_* (consumed by milo-mac)
#   /var/lib/milo/snapclient.env  → MILO_SNAPCLIENT_* (consumed by milo-snapclient-multiroom)
# =============================================================================

DEFAULT_SNAPCLIENT_CONFIG = {
    "buffer_time": 80,
    "fragments": 4,
}


def _atomic_write(path: str, content: str) -> None:
    """Write file atomically: temp file + fsync + os.replace."""
    temp_path = path + ".tmp"
    try:
        with open(temp_path, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(temp_path, path)
    except Exception:
        with contextlib.suppress(OSError):
            if os.path.exists(temp_path):
                os.remove(temp_path)
        raise


class RoutingEnv:
    """Writes /var/lib/milo/routing.env. Holds only MILO_MODE."""

    PATH = "/var/lib/milo/routing.env"

    @staticmethod
    def regenerate(multiroom_enabled: bool) -> None:
        """Regenerate routing.env from a boolean state.

        Sets os.environ["MILO_MODE"] as a side effect for in-process ALSA
        resolution (e.g., aplay invocations). Never read os.environ as truth —
        the only authoritative input is the explicit `multiroom_enabled` arg.
        """
        logger = logging.getLogger(__name__)
        mode_value = "multiroom" if bool(multiroom_enabled) else "direct"

        content = (
            "# Milo Audio Routing Environment\n"
            "# Auto-generated by Milo backend. Do not edit manually.\n"
            "\n"
            f"MILO_MODE={mode_value}\n"
        )

        try:
            _atomic_write(RoutingEnv.PATH, content)
        except Exception as e:
            logger.error(f"Failed to write {RoutingEnv.PATH}: {e}")
            raise RuntimeError(f"Failed to write routing.env: {e}")

        os.environ["MILO_MODE"] = mode_value
        logger.info(f"Updated routing.env: MODE={mode_value}")


class MacEnv:
    """Writes /var/lib/milo/mac.env. Holds ROC_* vars consumed by milo-mac."""

    PATH = "/var/lib/milo/mac.env"

    @staticmethod
    def regenerate(mac_config: Optional[Dict[str, Any]]) -> None:
        """Regenerate mac.env from a pre-loaded `mac` config dict.

        Pure function: validates and clamps values to allowed ranges, falls
        back to DEFAULT_ROC_CONFIG when fields are missing. The caller owns
        the settings read (consolidated in
        AudioRoutingService.regenerate_env_files).
        """
        logger = logging.getLogger(__name__)

        if not isinstance(mac_config, dict):
            mac_config = {}

        target_latency = mac_config.get("target_latency_ms", DEFAULT_ROC_CONFIG["target_latency_ms"])
        latency_profile = mac_config.get("latency_profile", DEFAULT_ROC_CONFIG["latency_profile"])
        frame_length = mac_config.get("frame_length_ms", DEFAULT_ROC_CONFIG["frame_length_ms"])

        try:
            target_latency = int(target_latency)
        except (TypeError, ValueError):
            target_latency = DEFAULT_ROC_CONFIG["target_latency_ms"]
        target_latency = max(20, min(500, target_latency))

        if latency_profile not in ALLOWED_LATENCY_PROFILES:
            latency_profile = DEFAULT_ROC_CONFIG["latency_profile"]

        try:
            frame_length = int(frame_length)
        except (TypeError, ValueError):
            frame_length = DEFAULT_ROC_CONFIG["frame_length_ms"]
        if frame_length not in ALLOWED_FRAME_LENGTHS:
            frame_length = DEFAULT_ROC_CONFIG["frame_length_ms"]

        content = (
            "# Milo ROC (Mac streaming) Environment\n"
            "# Auto-generated by Milo backend. Do not edit manually.\n"
            "\n"
            f"ROC_TARGET_LATENCY={target_latency}ms\n"
            f"ROC_LATENCY_PROFILE={latency_profile}\n"
            f"ROC_FRAME_LENGTH={frame_length}ms\n"
        )

        try:
            _atomic_write(MacEnv.PATH, content)
        except Exception as e:
            logger.error(f"Failed to write {MacEnv.PATH}: {e}")
            raise RuntimeError(f"Failed to write mac.env: {e}")

        logger.info(
            f"Updated mac.env: ROC latency={target_latency}ms profile={latency_profile} frame={frame_length}ms"
        )


class SnapclientEnv:
    """Writes /var/lib/milo/snapclient.env. Holds MILO_SNAPCLIENT_* vars consumed by milo-snapclient-multiroom."""

    PATH = "/var/lib/milo/snapclient.env"

    @staticmethod
    def regenerate(buffer_time: Any, fragments: Any) -> None:
        """Regenerate snapclient.env from pre-loaded buffer_time / fragments values.

        Pure function: validates and clamps inputs, falls back to
        DEFAULT_SNAPCLIENT_CONFIG when either is None. The caller owns the
        settings read (consolidated in
        AudioRoutingService.regenerate_env_files since Phase 4).
        """
        logger = logging.getLogger(__name__)

        if buffer_time is None:
            buffer_time = DEFAULT_SNAPCLIENT_CONFIG["buffer_time"]
        if fragments is None:
            fragments = DEFAULT_SNAPCLIENT_CONFIG["fragments"]

        try:
            buffer_time = int(buffer_time)
        except (TypeError, ValueError):
            buffer_time = DEFAULT_SNAPCLIENT_CONFIG["buffer_time"]
        buffer_time = max(10, min(200, buffer_time))

        try:
            fragments = int(fragments)
        except (TypeError, ValueError):
            fragments = DEFAULT_SNAPCLIENT_CONFIG["fragments"]
        fragments = max(2, min(8, fragments))

        content = (
            "# Milo Snapclient Environment\n"
            "# Auto-generated by Milo backend. Do not edit manually.\n"
            "\n"
            f"MILO_SNAPCLIENT_BUFFER_TIME={buffer_time}\n"
            f"MILO_SNAPCLIENT_FRAGMENTS={fragments}\n"
        )

        try:
            _atomic_write(SnapclientEnv.PATH, content)
        except Exception as e:
            logger.error(f"Failed to write {SnapclientEnv.PATH}: {e}")
            raise RuntimeError(f"Failed to write snapclient.env: {e}")

        logger.info(
            f"Updated snapclient.env: buffer_time={buffer_time}ms fragments={fragments}"
        )


class AudioRoutingService:
    """
    Audio routing service.

    `multiroom_enabled` is read directly from settings.json on every access
    (no in-memory cache). `equalizer_effects_enabled` is owned by
    CamillaDSPService and read through a property. The state machine reads
    both via these accessors when aggregating `full_state` for source/system
    broadcasts.
    """

    def __init__(self, get_source_callback: Optional[Callable] = None,
                 settings_service: Optional["SettingsService"] = None,
                 systemd_manager: Optional[SystemdServiceManager] = None,
                 snapcast_service=None, camilladsp_service=None):
        self.logger = logging.getLogger(__name__)
        self.service_manager = systemd_manager
        self.get_source = get_source_callback
        self.settings_service = settings_service
        self._initial_detection_done = False

        # Acyclic deps (constructor-injected). snapcast_websocket_service /
        # state_machine / volume_service close real cycles → set post-construction.
        self.snapcast_service = snapcast_service
        self.camilladsp_service = camilladsp_service
        self.snapcast_websocket_service = None
        self.state_machine: Optional["AudioStateMachine"] = None
        self.volume_service = None

        # Lock to guarantee atomicity of routing operations
        self._routing_lock = asyncio.Lock()
        self._bg = BackgroundTaskSet(self.logger, "routing")

        self.snapserver_service = "milo-snapserver-multiroom.service"
        self.snapclient_service = "milo-snapclient-multiroom.service"

    def set_snapcast_websocket_service(self, service) -> None:
        """Set SnapcastWebSocketService dependency."""
        self.snapcast_websocket_service = service

    def set_state_machine(self, state_machine: "AudioStateMachine") -> None:
        """Set state machine for event broadcasting."""
        self.state_machine = state_machine

    def set_volume_service(self, service) -> None:
        """Set VolumeService dependency."""
        self.volume_service = service

    def set_source_callback(self, callback: Callable) -> None:
        """Set callback to access audio source instances."""
        if not self.get_source:
            self.get_source = callback

    # === Helper methods ===

    @staticmethod
    def _to_bool(value) -> bool:
        """Convert various types to boolean safely."""
        if value is None:
            return False
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.lower() in ('true', '1', 'yes', 'on', 'enabled')
        return bool(value)

    # === State accessors ===
    # multiroom_enabled reads directly from settings.json (single source of
    # truth, no cache). equalizer_effects_enabled is owned by CamillaDSPService
    # — we proxy reads/writes through a get/set pair for _guarded_simple_toggle.

    async def _get_equalizer_effects_enabled(self) -> bool:
        return self.equalizer_effects_enabled

    async def _set_equalizer_effects_state(self, value: bool) -> None:
        if self.camilladsp_service:
            self.camilladsp_service.set_effects_enabled(value)

    @property
    def multiroom_enabled(self) -> bool:
        """Read multiroom enabled state from settings.json (sync, cache-backed).

        SettingsService.get_setting_sync returns a validated cached dict (the
        cache is populated through _validate_and_merge), so this is a hot-path
        dict lookup, not a disk read.
        """
        if not self.settings_service:
            return False
        return self._to_bool(self.settings_service.get_setting_sync('routing.multiroom_enabled'))

    @property
    def equalizer_effects_enabled(self) -> bool:
        if not self.camilladsp_service:
            return False
        return self.camilladsp_service.effects_enabled

    async def initialize(self) -> None:
        """Initializes service state"""
        if not self._initial_detection_done:
            await self._detect_initial_state()

    async def _detect_initial_state(self):
        """Reconcile derived artifacts and live state to match settings.json.

        Source of truth is settings.routing.multiroom_enabled (read via the
        property). This pass:
          1. Warms the settings cache via async load.
          2. Re-derives routing/mac/snapclient env files from settings
             (idempotent — bootstrap also wrote them in dependencies.py).
          3. Reconciles snapcast systemd state.
          4. Ensures CamillaDSP is running.

        Leaves _initial_detection_done = False on failure so the next caller
        retries detection.
        """
        try:
            self.logger.info("Initializing routing state with persistence...")

            # Warm the settings cache via async load. The validated dict
            # populated here backs every subsequent sync get_setting_sync call
            # (notably regenerate_env_files() below).
            if self.settings_service:
                await self.settings_service.get_setting('routing.multiroom_enabled')
            else:
                self.logger.warning("SettingsService not available, multiroom will read False")

            self.logger.info(
                f"Loaded state from settings: multiroom={self.multiroom_enabled}, "
                f"equalizer_effects={self.equalizer_effects_enabled}"
            )

            self.regenerate_env_files()
            await self._sync_snapcast_state()
            await self._initialize_camilladsp()

            self._initial_detection_done = True
            self.logger.info(
                f"Routing initialized: multiroom={self.multiroom_enabled}, "
                f"equalizer_effects={self.equalizer_effects_enabled}"
            )

            if self.multiroom_enabled:
                self._bg.spawn(
                    self._delayed_multiroom_sync(),
                    label="delayed_multiroom_sync",
                )

        except Exception as e:
            # Leave _initial_detection_done = False so a transient init failure
            # can be retried on the next caller (e.g., set_multiroom_enabled).
            self.logger.error(f"Error during initial state detection: {e}")

    async def _sync_snapcast_state(self) -> None:
        """Reconcile running Snapcast services with persisted multiroom state.

        Sole authoritative entry point for starting/stopping snapserver and
        snapclient. Source of truth: settings.routing.multiroom_enabled
        (mirrored in self.multiroom_enabled). Snapcast units carry no
        [Install] section, so they only run when this reconcile starts them.
        """
        snapcast_status = await self.get_snapcast_status()
        server_running = snapcast_status.get("server_active", False)
        client_running = snapcast_status.get("client_active", False)
        services_running = snapcast_status.get("multiroom_available", False)
        target_mode = "multiroom" if self.multiroom_enabled else "direct"

        self.logger.info(
            f"SNAPCAST_RECONCILE: source_of_truth=settings.routing.multiroom_enabled={self.multiroom_enabled} "
            f"(target={target_mode}); observed snapserver={server_running}, snapclient={client_running}"
        )

        if self.multiroom_enabled and not services_running:
            self.logger.info("SNAPCAST_RECONCILE: starting snapcast services")
            started = await self._start_snapcast()
            self.logger.info(f"SNAPCAST_RECONCILE: start result={started}")
        elif not self.multiroom_enabled and (server_running or client_running):
            self.logger.info("SNAPCAST_RECONCILE: stopping snapcast services")
            stopped = await self._stop_snapcast()
            self.logger.info(f"SNAPCAST_RECONCILE: stop result={stopped}")
        else:
            self.logger.info(f"SNAPCAST_RECONCILE: already coherent for {target_mode} mode, no action")

    async def _initialize_camilladsp(self) -> None:
        """Ensure CamillaDSP systemd service is running.

        Connection + effect restore are owned by CamillaDSPService's own
        _connection_loop (driven by initialize()), which runs strictly after
        _load_saved_config() has populated _filters from equalizer.json.
        Doing the restore here would race with _load_saved_config and could
        push stale (default-zero) gains to the daemon if camilladsp was
        already up (PartOf= cycles it with milo-backend, so the sleep below
        is skipped).
        """
        camilladsp_running = await self.service_manager.is_active("milo-camilladsp.service")
        if not camilladsp_running:
            self.logger.info("Starting CamillaDSP service (always required for volume control)")
            await self.service_manager.start("milo-camilladsp.service")
            await asyncio.sleep(1.0)  # Give daemon time to start

    @handle_errors(default=None)
    async def _delayed_multiroom_sync(self):
        """Sync client volumes from equalizer once snapserver is actually ready.

        Boot-time counterpart of the post-transition sync: waits on a real
        readiness condition (snapserver JSON-RPC answering) instead of a blind
        constant, then pushes equalizer volumes to the connected clients.
        """
        self.logger.info(f"[{time.time():.3f}] DELAYED_SYNC: Waiting for snapserver readiness...")
        if not await self._wait_snapserver_ready(timeout=15.0):
            self.logger.warning(
                f"[{time.time():.3f}] DELAYED_SYNC: snapserver not ready in time, skipping startup sync"
            )
            return

        # Check multiroom is still enabled
        if not self.multiroom_enabled:
            self.logger.info(f"[{time.time():.3f}] DELAYED_SYNC: Multiroom disabled, skipping sync")
            return

        # Sync volumes from equalizer
        if self.volume_service:
            self.logger.info(f"[{time.time():.3f}] DELAYED_SYNC: Starting sync_all_clients_from_equalizer")
            await self.volume_service.sync_all_clients_from_equalizer()
            self.logger.info(f"[{time.time():.3f}] DELAYED_SYNC: sync_all_clients_from_equalizer complete")
        else:
            self.logger.warning("VolumeService not available for equalizer sync")

    async def _guarded_simple_toggle(
        self,
        get_fn,
        set_fn,
        desired: bool,
        operation_name: str,
        body_fn,
    ) -> bool:
        """
        Execute a *simple* state toggle with lock, idempotency check, and rollback.

        Used by lightweight togglers (e.g. equalizer effects) where there is no
        service start/stop and no source restart. The multiroom transition has
        its own idempotent reconcile flow in `set_multiroom_enabled`.

        Args:
            get_fn: async () -> bool — read current state
            set_fn: async (bool) -> None — set state + any side effects
            desired: Target state value
            operation_name: For logging (e.g., "equalizer_effects")
            body_fn: async (bool) -> bool — the transition body, returns success
        """
        async with self._routing_lock:
            current = await get_fn()
            if current == desired:
                self.logger.info(f"{operation_name} already {'enabled' if desired else 'disabled'}")
                return True

            old_state = current
            try:
                await set_fn(desired)
                success = await body_fn(desired)
                if not success:
                    await set_fn(old_state)
                    self.logger.error(f"Failed to transition {operation_name} to {desired}, reverting to {old_state}")
                    return False
                return True
            except Exception as e:
                await set_fn(old_state)
                self.logger.error(f"Error changing {operation_name} state: {e}")
                return False

    async def set_multiroom_enabled(self, enabled: bool, active_source: AudioSource = None) -> bool:
        """Enable/disable multiroom mode via idempotent reconcile.

        No phased commit, no rollback. Each step is either idempotent or a
        single atomic write:
          1. Pre-broadcast (UI loading state).
          2. `_apply_transition`: stop source → reconcile snapcast → write
             routing.env (derived) → start source (best-effort).
          3. Persist settings (strict; raises on disk failure).
          4. Post-transition (WS readiness, volume sync, ready broadcast).

        On any exception in steps 1-3: log + broadcast `multiroom_error`,
        return False. Step 4 is genuinely best-effort: `_apply_transition` has
        already started snapserver + snapclient, and both snapclient and the
        control WS auto-reconnect as the daemon finishes coming up — so a
        WS-not-ready-yet or a transient volume-push miss is self-healing
        (delayed sync + client-connect retry). It is logged (warning) but does
        NOT fail the enable — the mode IS committed, so we always broadcast
        `state_changed` and return True. Failing here would contradict the
        committed mode (toggle stuck off, HTTP 500) with no upside. (A genuinely
        dead snapserver — unit active but JSON-RPC never answering — also fails
        `_start_snapcast`'s readiness poll, which logs it; it is a systemic fault
        surfaced elsewhere, not something this best-effort step should re-raise.)
        The system is in either old-consistent or new-consistent state; next
        backend boot re-reconciles via `_detect_initial_state` and
        `_sync_snapcast_state`. No rollback path.

        routing.env is regenerated before settings is persisted so the source
        unit restarted inside `_apply_transition` picks up the new MILO_MODE.
        If settings persist fails afterwards, the next boot re-derives
        routing.env from the (still-old) settings.
        """
        if not self._initial_detection_done:
            await self._detect_initial_state()

        async with self._routing_lock:
            old_state = self.multiroom_enabled
            if old_state == enabled:
                self.logger.info(f"multiroom already {'enabled' if enabled else 'disabled'}")
                return True

            self.logger.info(f"Reconciling multiroom {old_state} → {enabled}")

            try:
                await self._broadcast_transition_event(enabled)
                await self._apply_transition(enabled, active_source)
                if self.settings_service:
                    await self.settings_service.set_setting_strict(
                        'routing.multiroom_enabled', enabled
                    )
            except Exception as e:
                self.logger.error(f"multiroom transition failed: {e}")
                await self._broadcast_error(enabled)
                return False

            # Physical mode is committed above. Follow-up sync (WS readiness,
            # volume push, multiroom_ready) is best-effort and self-healing —
            # it logs warnings but never fails the transition.
            await self._post_transition_setup_best_effort(enabled)

            # multiroom_changed: the discriminator Milo-Mac keys on (only this
            # emitter sets it); the new mode itself travels in the injected
            # full_state.
            if self.state_machine:
                await self.state_machine.broadcast(
                    SystemStateChanged(source="routing", multiroom_changed=True)
                )

            self.logger.info(f"Multiroom transition complete: {enabled}")
            return True

    async def _apply_transition(self, enabled: bool, active_source: AudioSource = None) -> None:
        """Release source, reconcile snapcast, regenerate routing.env, re-acquire source.

        Source release/re-acquire goes through release_for_reroute() /
        acquire_after_reroute() (default = stop()/start()) so a source that holds
        its upstream link in a separate process from the ALSA writer (Bluetooth)
        can rebounce only the writer and keep the sender connected.

        Acquires the state machine's exclusive_transition() context to prevent
        concurrent source lifecycle operations with `transition_to_source()`.
        Lock order is always: `_routing_lock` (held by caller) → transition lock.

        Snapcast reconcile is idempotent. routing.env is regenerated AFTER
        snapcast settles and BEFORE the source restart so systemd sees the new
        MILO_MODE when it starts the source unit. Source start is best-effort
        — a failing source no longer fails the whole transition.

        Raises only when snapcast services fail to start (multiroom→enabled)
        or when the state machine is unavailable. Every path that does not end
        in the source broadcasting its own start — the raise, and both step-5
        failure branches — republishes the source's real state, so the STARTING
        posted at step 1 is never the last word.
        """
        if not self.state_machine:
            raise RuntimeError("State machine not available for routing transition")

        target_mode = "multiroom" if enabled else "direct"
        source_instance = None
        if active_source and self.get_source:
            source_instance = self.get_source(active_source)

        async with self.state_machine.exclusive_transition():
            # Step 1: Notify STARTING state to show loading UI.
            # metadata=None: state-only change — keep the current track metadata
            # visible during the reroute (update_source_state replaces metadata
            # when a payload is given, so passing one here would wipe the track).
            if source_instance:
                await self.state_machine.update_source_state(
                    source=active_source,
                    new_state=SourceState.STARTING,
                    metadata=None
                )

            try:
                # Step 2: Stop source FIRST to release ALSA device before routing change.
                # Critical: in direct mode the source holds camilladsp; in multiroom mode
                # snapclient needs the same device.
                if source_instance:
                    self.logger.info(f"Releasing source {active_source.value} to free ALSA device")
                    await source_instance.release_for_reroute()
                    await asyncio.sleep(0.5)  # Wait for ALSA to release

                # Step 3: Reconcile snapcast services to target (idempotent).
                # Both branches raise on failure — a silent stop would leave
                # snapclient holding the ALSA loopback while routing.env flips to
                # direct, recreating the 2026-05-13 desync.
                if enabled:
                    self.logger.info("Starting snapcast services")
                    if not await self._start_snapcast():
                        raise RuntimeError("Failed to start snapcast services")
                else:
                    self.logger.info("Stopping snapcast services")
                    if not await self._stop_snapcast():
                        raise RuntimeError("Failed to stop snapcast services")

                # Step 4: Regenerate routing.env so source unit picks up new MILO_MODE
                RoutingEnv.regenerate(enabled)

                # Step 5: Restart source with new routing — best-effort.
                # A source failure here doesn't fail the transition; the multiroom
                # mode is correctly set and the user can retry source playback.
                if source_instance:
                    self.logger.info(f"Re-acquiring source {active_source.value} for {target_mode} mode")
                    reacquired = False
                    try:
                        reacquired = await source_instance.acquire_after_reroute()
                        if not reacquired:
                            self.logger.warning(
                                f"Source {active_source.value} re-acquire returned False after "
                                f"{target_mode} transition (transition still considered successful)"
                            )
                    except Exception as e:
                        self.logger.warning(
                            f"Source start failed after {target_mode} transition (non-fatal): {e}"
                        )

                    if not reacquired:
                        # The success path relies on the source's own start
                        # broadcast to replace the STARTING published at step 1;
                        # neither of these two branches has one. Without this the
                        # card spins for the rest of the session — re-tapping the
                        # source is a no-op because the state machine already
                        # believes it is starting, and only switching sources
                        # recovers. Same recipe as the except below.
                        await self.state_machine.update_source_state(
                            source=active_source,
                            new_state=source_instance.state,
                            metadata=source_instance.metadata,
                        )
            except Exception:
                # Step 1 published STARTING and nothing else republishes on this
                # path: the caller broadcasts multiroom_error and returns, so the
                # card would show "Starting" for the rest of the session. Same
                # recipe as transition_to_source's post-start resync — read the
                # source's real state back rather than guess one.
                if source_instance:
                    await self.state_machine.update_source_state(
                        source=active_source,
                        new_state=source_instance.state,
                        metadata=source_instance.metadata,
                    )
                raise

    async def _post_transition_setup_best_effort(self, enabled: bool) -> None:
        """Post-transition: WebSocket lifecycle, volume sync, and ready broadcast.

        Settings + routing.env are already committed by the caller and snapserver
        has been started, so every step here is best-effort and self-healing: a
        WS-not-ready-yet or a transient volume-push miss is recovered by the
        delayed sync + client-connect retries. Failures are logged (warning) but
        never fail the transition — the physical mode has switched regardless.
        """
        # WebSocket connection lifecycle + readiness wait
        try:
            if self.snapcast_websocket_service:
                if enabled:
                    await self.snapcast_websocket_service.start_connection()
                    self.logger.info("POST_TRANSITION: Waiting for Snapcast WebSocket to be ready...")
                    if await self.snapcast_websocket_service.wait_for_ready(timeout=15.0):
                        self.logger.info("POST_TRANSITION: Snapcast WebSocket is ready")
                    else:
                        self.logger.warning(
                            "POST_TRANSITION: Snapcast WebSocket not ready after 15s — "
                            "volume sync will heal via delayed sync / client-connect"
                        )
                else:
                    await self.snapcast_websocket_service.stop_connection()
        except Exception as e:
            self.logger.warning(f"POST_TRANSITION: WS lifecycle failed (non-fatal): {e}")

        # Volume mode update + client sync
        try:
            if self.volume_service:
                target_volume = await self.volume_service.update_volume_mode(enabled)
                if enabled:
                    if target_volume is not None:
                        self.logger.info(
                            f"POST_TRANSITION: Pushing volume ({target_volume:.1f}dB) to all clients..."
                        )
                        if not await self.volume_service.push_volume_to_all_clients(target_volume):
                            self.logger.warning("POST_TRANSITION: push_volume_to_all_clients returned failure")
                    else:
                        # DAC mode: sync client volumes from equalizers
                        await self.volume_service.sync_all_clients_from_equalizer()
        except Exception as e:
            self.logger.warning(f"POST_TRANSITION: Volume sync failed (non-fatal): {e}")

        # multiroom_ready — clears the UI transition spinner. Fires whenever
        # enabling (the mode IS up); volumes trail in via the retries above.
        if enabled and self.state_machine:
            try:
                self.logger.info("POST_TRANSITION: Broadcasting multiroom_ready event")
                await self.state_machine.broadcast(RoutingMultiroomReady())
            except Exception as e:
                self.logger.warning(f"POST_TRANSITION: multiroom_ready broadcast failed: {e}")

    async def _broadcast_transition_event(self, enabled: bool) -> None:
        """Broadcast pre-transition event to let frontend react."""
        if not self.state_machine:
            self.logger.warning("state_machine not available, cannot broadcast event")
            return
        event = RoutingMultiroomEnabling() if enabled else RoutingMultiroomDisabling()
        self.logger.info(f"Broadcasting {event.TYPE} event")
        await self.state_machine.broadcast(event)
        await asyncio.sleep(0.1)  # Let frontend react

    async def _broadcast_error(self, attempted_state: bool) -> None:
        """Broadcast a multiroom_error event after a failed transition."""
        if not self.state_machine:
            return
        try:
            await self.state_machine.broadcast(RoutingMultiroomError(
                reason="enable_failed" if attempted_state else "disable_failed",
            ))
        except Exception as e:
            self.logger.warning(f"multiroom_error broadcast failed: {e}")

    async def set_equalizer_effects_enabled(self, enabled: bool) -> bool:
        """
        Enables/disables equalizer effects (not the service itself).

        CamillaDSP service stays ALWAYS running. This toggle only controls:
        - EQ filters (enabled/bypassed)
        - Compressor (enabled/bypassed)
        - Loudness (enabled/bypassed)

        Volume control via CamillaDSP is ALWAYS active regardless of this setting.
        """
        async def body(enabled: bool) -> bool:
            self.logger.info(f"{'Enabling' if enabled else 'Bypassing'} Equalizer effects")

            success = True
            if self.camilladsp_service:
                if enabled:
                    success = await self.camilladsp_service.restore_effects()
                    self.logger.info("Equalizer effects restored from settings" if success
                                     else "Failed to restore Equalizer effects")
                else:
                    success = await self.camilladsp_service.bypass_effects()
                    self.logger.info("Equalizer effects bypassed (volume unchanged)" if success
                                     else "Failed to bypass Equalizer effects")

                if not success:
                    return False

            if self.state_machine:
                await self.state_machine.broadcast(EqualizerEnabledChanged(enabled=enabled))

            if self.settings_service:
                await self.settings_service.set_setting('routing.equalizer_effects_enabled', enabled)

            self.logger.info(f"Equalizer effects {'enabled' if enabled else 'bypassed'}")
            return True

        success = await self._guarded_simple_toggle(
            self._get_equalizer_effects_enabled, self._set_equalizer_effects_state,
            enabled, "equalizer_effects", body,
        )
        # Broadcast final state after successful transition — full_state
        # aggregation reads equalizer_effects_enabled from camilladsp.
        if success and self.state_machine:
            await self.state_machine.broadcast(SystemStateChanged(source="equalizer"))
        return success

    def regenerate_env_files(self) -> None:
        """Re-derive all three env files (routing/mac/snapclient) from settings.

        Sole entry point for the boot-time env-file write and for the
        `_detect_initial_state` reconcile pass. Reads `settings_service`
        synchronously (via the validation-strict `get_setting_sync`) and passes
        the extracted values to each pure env writer.

        This is the sole consolidation point for the sync settings read:
        - Only this method and the `multiroom_enabled` property call
          `get_setting_sync`. Every other reader goes async.
        - Multiroom-only transitions still call `RoutingEnv.regenerate(enabled)`
          directly from `_apply_transition` (targeted single-file write —
          mac.env / snapclient.env are unchanged by a mode toggle).
        """
        if not self.settings_service:
            RoutingEnv.regenerate(False)
            MacEnv.regenerate(None)
            SnapclientEnv.regenerate(None, None)
            return

        multiroom = self._to_bool(
            self.settings_service.get_setting_sync('routing.multiroom_enabled')
        )
        mac_config = self.settings_service.get_setting_sync('mac')
        buffer_time = self.settings_service.get_setting_sync('multiroom.snapclient_buffer_time')
        fragments = self.settings_service.get_setting_sync('multiroom.snapclient_fragments')

        RoutingEnv.regenerate(multiroom)
        MacEnv.regenerate(mac_config)
        SnapclientEnv.regenerate(buffer_time, fragments)

    async def _wait_snapserver_ready(self, timeout: float = 10.0) -> bool:
        """Wait for snapserver's JSON-RPC to answer (real-condition, wall-clock).

        Thin guard around ``SnapcastService.wait_until_available`` — the poll
        itself lives with the service that owns ``is_available``.
        """
        if not self.snapcast_service:
            self.logger.warning("SnapcastService unavailable, cannot confirm snapserver readiness")
            return False
        return await self.snapcast_service.wait_until_available(timeout)

    @handle_errors(default=False)
    async def _start_snapcast(self) -> bool:
        """Starts snapcast services and waits for snapserver readiness"""
        success = await self.service_manager.start(self.snapserver_service)
        if not success:
            return False

        # Wait for snapserver JSON-RPC to answer before starting snapclient —
        # a real-condition poll, no blind pre-sleep.
        if await self._wait_snapserver_ready(timeout=10.0):
            self.logger.info("Snapserver is ready")
        else:
            self.logger.warning("Snapserver not ready after 10s, proceeding anyway")

        success = await self.service_manager.start(self.snapclient_service)
        return success

    async def _stop_snapcast(self) -> bool:
        """Stop snapcast services. Returns True iff both stopped cleanly.

        Symmetric to ``_start_snapcast``: returns bool, never swallows.
        A silent failure here would leave snapclient holding ``hw:Loopback,0,0``
        via the camilladsp plug while ``routing.env=direct`` redirected
        ``milo_roc`` to the same device — the original 2026-05-13 incident
        class. Caller is expected to raise on False so the transition does
        not persist a half-applied state.
        """
        client_ok = await self.service_manager.stop(self.snapclient_service)
        server_ok = await self.service_manager.stop(self.snapserver_service)
        if not (client_ok and server_ok):
            self.logger.error(
                f"snapcast stop incomplete: client_ok={client_ok}, server_ok={server_ok}"
            )
        return client_ok and server_ok

    async def cleanup(self) -> None:
        """Drain the delayed-multiroom-sync task (it waits up to 15s on snapserver)."""
        await self._bg.cancel_all()

    def get_state(self) -> Dict[str, bool]:
        """
        Gets current routing state from single source of truth

        NEW: Returns a dict instead of AudioRoutingState (which no longer exists)
        """
        return {
            "multiroom_enabled": self.multiroom_enabled,
            "equalizer_effects_enabled": self.equalizer_effects_enabled
        }

    async def get_snapcast_status(self) -> Dict[str, Any]:
        """Gets snapcast services status"""
        try:
            server_active = await self.service_manager.is_active(self.snapserver_service)
            client_active = await self.service_manager.is_active(self.snapclient_service)

            return {
                "server_active": server_active,
                "client_active": client_active,
                "multiroom_available": server_active and client_active
            }
        except Exception as e:
            self.logger.error(f"Error getting snapcast status: {e}")
            return {"server_active": False, "client_active": False, "multiroom_available": False}
