/**
 * Taddy API Language enums (ISO 639-2 compliant)
 * 197 languages with French labels
 * Most common languages listed first, then alphabetical
 */

// Top 20 most common languages (in order of podcast availability)
const COMMON_LANGUAGES = [
  { label: 'Français', value: 'FRENCH' },
  { label: 'Anglais', value: 'ENGLISH' },
  { label: 'Espagnol', value: 'SPANISH' },
  { label: 'Allemand', value: 'GERMAN' },
  { label: 'Italien', value: 'ITALIAN' },
  { label: 'Portugais', value: 'PORTUGUESE' },
  { label: 'Néerlandais', value: 'DUTCH_FLEMISH' },
  { label: 'Russe', value: 'RUSSIAN' },
  { label: 'Chinois', value: 'CHINESE' },
  { label: 'Japonais', value: 'JAPANESE' },
  { label: 'Coréen', value: 'KOREAN' },
  { label: 'Arabe', value: 'ARABIC' },
  { label: 'Hindi', value: 'HINDI' },
  { label: 'Polonais', value: 'POLISH' },
  { label: 'Turc', value: 'TURKISH' },
  { label: 'Suédois', value: 'SWEDISH' },
  { label: 'Norvégien', value: 'NORWEGIAN' },
  { label: 'Danois', value: 'DANISH' },
  { label: 'Finnois', value: 'FINNISH' },
  { label: 'Grec', value: 'GREEK' },
];

// Remaining languages in French alphabetical order
const OTHER_LANGUAGES = [
  { label: 'Abkhaze', value: 'ABKHAZIAN' },
  { label: 'Afar', value: 'AFAR' },
  { label: 'Afrikaans', value: 'AFRIKAANS' },
  { label: 'Akan', value: 'AKAN' },
  { label: 'Albanais', value: 'ALBANIAN' },
  { label: 'Amharique', value: 'AMHARIC' },
  { label: 'Aragonais', value: 'ARAGONESE' },
  { label: 'Arménien', value: 'ARMENIAN' },
  { label: 'Assamais', value: 'ASSAMESE' },
  { label: 'Avaric', value: 'AVARIC' },
  { label: 'Avestique', value: 'AVESTAN' },
  { label: 'Aymara', value: 'AYMARA' },
  { label: 'Azéri', value: 'AZERBAIJANI' },
  { label: 'Bambara', value: 'BAMBARA' },
  { label: 'Bachkir', value: 'BASHKIR' },
  { label: 'Basque', value: 'BASQUE' },
  { label: 'Biélorusse', value: 'BELARUSIAN' },
  { label: 'Bengali', value: 'BENGALI' },
  { label: 'Langues biharis', value: 'BIHARI_LANGUAGES' },
  { label: 'Bichelamar', value: 'BISLAMA' },
  { label: 'Bosniaque', value: 'BOSNIAN' },
  { label: 'Breton', value: 'BRETON' },
  { label: 'Bulgare', value: 'BULGARIAN' },
  { label: 'Birman', value: 'BURMESE' },
  { label: 'Catalan', value: 'VALENCIAN_CATALAN' },
  { label: 'Chamorro', value: 'CHAMORRO' },
  { label: 'Tchétchène', value: 'CHECHEN' },
  { label: 'Chichewa', value: 'CHICHEWA_CHEWA_NYANJA' },
  { label: 'Cingalais', value: 'SINHALA' },
  { label: 'Cornique', value: 'CORNISH' },
  { label: 'Corse', value: 'CORSICAN' },
  { label: 'Cree', value: 'CREE' },
  { label: 'Croate', value: 'CROATIAN' },
  { label: 'Dhivehi', value: 'DHIVEHI_MALDIVIAN' },
  { label: 'Dzongkha', value: 'DZONGKHA' },
  { label: 'Écossais', value: 'GAELIC' },
  { label: 'Espéranto', value: 'ESPERANTO' },
  { label: 'Estonien', value: 'ESTONIAN' },
  { label: 'Éwé', value: 'EWE' },
  { label: 'Féroïen', value: 'FAROESE' },
  { label: 'Fidjien', value: 'FIJIAN' },
  { label: 'Frison occidental', value: 'WESTERN_FRISIAN' },
  { label: 'Peul', value: 'FULAH' },
  { label: 'Galicien', value: 'GALICIAN' },
  { label: 'Ganda', value: 'GANDA' },
  { label: 'Géorgien', value: 'GEORGIAN' },
  { label: 'Kikuyu', value: 'GIKUYU' },
  { label: 'Guarani', value: 'GUARANI' },
  { label: 'Gujarati', value: 'GUJARATI' },
  { label: 'Créole haïtien', value: 'HAITIAN_CREOLE' },
  { label: 'Haoussa', value: 'HAUSA' },
  { label: 'Hébreu', value: 'HEBREW' },
  { label: 'Héréro', value: 'HERERO' },
  { label: 'Hiri motu', value: 'HIRI_MOTU' },
  { label: 'Hongrois', value: 'HUNGARIAN' },
  { label: 'Islandais', value: 'ICELANDIC' },
  { label: 'Ido', value: 'IDO' },
  { label: 'Igbo', value: 'IGBO' },
  { label: 'Indonésien', value: 'INDONESIAN' },
  { label: 'Interlingua', value: 'INTERLINGUA' },
  { label: 'Interlingue', value: 'INTERLINGUE_OCCIDENTAL' },
  { label: 'Inuktitut', value: 'INUKTITUT' },
  { label: 'Inupiaq', value: 'INUPIAQ' },
  { label: 'Irlandais', value: 'IRISH' },
  { label: 'Javanais', value: 'JAVANESE' },
  { label: 'Kalaallisut', value: 'KALAALLISUT_GREENLANDIC' },
  { label: 'Kannada', value: 'KANNADA' },
  { label: 'Kanouri', value: 'KANURI' },
  { label: 'Kashmiri', value: 'KASHMIRI' },
  { label: 'Kazakh', value: 'KAZAKH' },
  { label: 'Khmer central', value: 'CENTRAL_KHMER' },
  { label: 'Kikongo', value: 'KONGO' },
  { label: 'Kinyarwanda', value: 'KINYARWANDA' },
  { label: 'Kirghiz', value: 'KYRGYZ' },
  { label: 'Komi', value: 'KOMI' },
  { label: 'Kurde', value: 'KURDISH' },
  { label: 'Kuanyama', value: 'KWANYAMA' },
  { label: 'Lao', value: 'LAO' },
  { label: 'Latin', value: 'LATIN' },
  { label: 'Letton', value: 'LATVIAN' },
  { label: 'Letzeburgesch', value: 'LETZEBURGESCH' },
  { label: 'Limbourgeois', value: 'LIMBURGISH' },
  { label: 'Lingala', value: 'LINGALA' },
  { label: 'Lituanien', value: 'LITHUANIAN' },
  { label: 'Luba-katanga', value: 'LUBA_KATANGA' },
  { label: 'Macédonien', value: 'MACEDONIAN' },
  { label: 'Malgache', value: 'MALAGASY' },
  { label: 'Malais', value: 'MALAY' },
  { label: 'Malayalam', value: 'MALAYALAM' },
  { label: 'Maltais', value: 'MALTESE' },
  { label: 'Mannois', value: 'MANX' },
  { label: 'Maori', value: 'MAORI' },
  { label: 'Marathi', value: 'MARATHI' },
  { label: 'Marshallais', value: 'MARSHALLESE' },
  { label: 'Mongol', value: 'MONGOLIAN' },
  { label: 'Nauruan', value: 'NAURU' },
  { label: 'Navajo', value: 'NAVAJO' },
  { label: 'Ndébélé du Nord', value: 'NORTH_NDEBELE' },
  { label: 'Ndébélé du Sud', value: 'SOUTH_NDEBELE' },
  { label: 'Ndonga', value: 'NDONGA' },
  { label: 'Népalais', value: 'NEPALI' },
  { label: 'Norvégien bokmål', value: 'NORWEGIAN_BOKMAL' },
  { label: 'Norvégien nynorsk', value: 'NORWEGIAN_NYNORSK' },
  { label: 'Nuosu', value: 'NUOSU_SICHUAN_YI' },
  { label: 'Occitan', value: 'OCCITAN' },
  { label: 'Ojibwé', value: 'OJIBWA' },
  { label: 'Oriya', value: 'ORIYA' },
  { label: 'Oromo', value: 'OROMO' },
  { label: 'Ossète', value: 'OSSETIAN' },
  { label: 'Pali', value: 'PALI' },
  { label: 'Pachto', value: 'PASHTO' },
  { label: 'Persan', value: 'FARSI' },
  { label: 'Pendjabi', value: 'PUNJABI' },
  { label: 'Quechua', value: 'QUECHUA' },
  { label: 'Romanche', value: 'ROMANSH' },
  { label: 'Roumain', value: 'ROMANIAN_MOLDOVAN' },
  { label: 'Rundi', value: 'RUNDI' },
  { label: 'Same du Nord', value: 'NORTHERN_SAMI' },
  { label: 'Samoan', value: 'SAMOAN' },
  { label: 'Sango', value: 'SANGO' },
  { label: 'Sanskrit', value: 'SANSKRIT' },
  { label: 'Sarde', value: 'SARDINIAN' },
  { label: 'Serbe', value: 'SERBIAN' },
  { label: 'Shona', value: 'SHONA' },
  { label: 'Sindhi', value: 'SINDHI' },
  { label: 'Slovaque', value: 'SLOVAK' },
  { label: 'Slovène', value: 'SLOVENIAN' },
  { label: 'Somali', value: 'SOMALI' },
  { label: 'Sotho du Sud', value: 'SOTHO' },
  { label: 'Soundanais', value: 'SUNDANESE' },
  { label: 'Swahili', value: 'SWAHILI' },
  { label: 'Swati', value: 'SWATI' },
  { label: 'Slave d\'Église', value: 'CHURCH_SLAVONIC' },
  { label: 'Tagalog', value: 'TAGALOG' },
  { label: 'Tahitien', value: 'TAHITIAN' },
  { label: 'Tadjik', value: 'TAJIK' },
  { label: 'Tamoul', value: 'TAMIL' },
  { label: 'Tatar', value: 'TATAR' },
  { label: 'Tchèque', value: 'CZECH' },
  { label: 'Télougou', value: 'TELUGU' },
  { label: 'Thaï', value: 'THAI' },
  { label: 'Tibétain', value: 'TIBETAN' },
  { label: 'Tigrigna', value: 'TIGRINYA' },
  { label: 'Tongien', value: 'TONGA' },
  { label: 'Tsonga', value: 'TSONGA' },
  { label: 'Tswana', value: 'TSWANA' },
  { label: 'Turkmène', value: 'TURKMEN' },
  { label: 'Twi', value: 'TWI' },
  { label: 'Tchétchène', value: 'CHECHEN' },
  { label: 'Tchouvache', value: 'CHUVASH' },
  { label: 'Ukrainien', value: 'UKRAINIAN' },
  { label: 'Ourdou', value: 'URDU' },
  { label: 'Ouïghour', value: 'UYGHUR' },
  { label: 'Ouzbek', value: 'UZBEK' },
  { label: 'Venda', value: 'VENDA' },
  { label: 'Vietnamien', value: 'VIETNAMESE' },
  { label: 'Volapük', value: 'VOLAPUK' },
  { label: 'Wallon', value: 'WALLOON' },
  { label: 'Gallois', value: 'WELSH' },
  { label: 'Wolof', value: 'WOLOF' },
  { label: 'Xhosa', value: 'XHOSA' },
  { label: 'Yiddish', value: 'YIDDISH' },
  { label: 'Yoruba', value: 'YORUBA' },
  { label: 'Zhuang', value: 'ZHUANG' },
  { label: 'Zoulou', value: 'ZULU' },
];

export const PODCAST_LANGUAGES = [...COMMON_LANGUAGES, ...OTHER_LANGUAGES];

/**
 * Creates dropdown options for podcast languages
 * @param {string} allLabel - Label for "All Languages" option
 * @returns {Array} Array of {label, value} objects for dropdown
 */
export function createPodcastLanguageOptions(allLabel = 'Toutes les langues') {
  return [
    { label: allLabel, value: '' },
    ...PODCAST_LANGUAGES
  ];
}
