/**
 * Taddy API Country enums (ISO 3166-1 compliant)
 * 264 countries with French labels
 */

export const PODCAST_COUNTRIES = [
  { label: 'Afghanistan', value: 'AFGHANISTAN' },
  { label: 'Afrique du Sud', value: 'SOUTH_AFRICA' },
  { label: 'Albanie', value: 'ALBANIA' },
  { label: 'Algérie', value: 'ALGERIA' },
  { label: 'Allemagne', value: 'GERMANY' },
  { label: 'Andorre', value: 'ANDORRA' },
  { label: 'Angola', value: 'ANGOLA' },
  { label: 'Anguilla', value: 'ANGUILLA' },
  { label: 'Antarctique', value: 'ANTARCTICA' },
  { label: 'Antigua-et-Barbuda', value: 'ANTIGUA_AND_BARBUDA' },
  { label: 'Arabie Saoudite', value: 'SAUDI_ARABIA' },
  { label: 'Argentine', value: 'ARGENTINA' },
  { label: 'Arménie', value: 'ARMENIA' },
  { label: 'Aruba', value: 'ARUBA' },
  { label: 'Australie', value: 'AUSTRALIA' },
  { label: 'Autriche', value: 'AUSTRIA' },
  { label: 'Azerbaïdjan', value: 'AZERBAIJAN' },
  { label: 'Bahamas', value: 'BAHAMAS' },
  { label: 'Bahreïn', value: 'BAHRAIN' },
  { label: 'Bangladesh', value: 'BANGLADESH' },
  { label: 'Barbade', value: 'BARBADOS' },
  { label: 'Belgique', value: 'BELGIUM' },
  { label: 'Belize', value: 'BELIZE' },
  { label: 'Bénin', value: 'BENIN' },
  { label: 'Bermudes', value: 'BERMUDA' },
  { label: 'Bhoutan', value: 'BHUTAN' },
  { label: 'Biélorussie', value: 'BELARUS' },
  { label: 'Bolivie', value: 'BOLIVIA_PLURINATIONAL_STATE_OF' },
  { label: 'Bosnie-Herzégovine', value: 'BOSNIA_AND_HERZEGOVINA' },
  { label: 'Botswana', value: 'BOTSWANA' },
  { label: 'Brésil', value: 'BRAZIL' },
  { label: 'Brunei', value: 'BRUNEI_DARUSSALAM' },
  { label: 'Bulgarie', value: 'BULGARIA' },
  { label: 'Burkina Faso', value: 'BURKINA_FASO' },
  { label: 'Burundi', value: 'BURUNDI' },
  { label: 'Cambodge', value: 'CAMBODIA' },
  { label: 'Cameroun', value: 'CAMEROON' },
  { label: 'Canada', value: 'CANADA' },
  { label: 'Cap-Vert', value: 'CABO_VERDE' },
  { label: 'Chili', value: 'CHILE' },
  { label: 'Chine', value: 'CHINA' },
  { label: 'Chypre', value: 'CYPRUS' },
  { label: 'Colombie', value: 'COLOMBIA' },
  { label: 'Comores', value: 'COMOROS' },
  { label: 'Congo', value: 'CONGO' },
  { label: 'Corée du Nord', value: 'KOREA_NORTH' },
  { label: 'Corée du Sud', value: 'KOREA_SOUTH' },
  { label: 'Costa Rica', value: 'COSTA_RICA' },
  { label: 'Côte d\'Ivoire', value: 'COTE_D_IVOIRE' },
  { label: 'Croatie', value: 'CROATIA' },
  { label: 'Cuba', value: 'CUBA' },
  { label: 'Curaçao', value: 'CURACAO' },
  { label: 'Danemark', value: 'DENMARK' },
  { label: 'Djibouti', value: 'DJIBOUTI' },
  { label: 'Dominique', value: 'DOMINICA' },
  { label: 'Égypte', value: 'EGYPT' },
  { label: 'Émirats Arabes Unis', value: 'UNITED_ARAB_EMIRATES' },
  { label: 'Équateur', value: 'ECUADOR' },
  { label: 'Érythrée', value: 'ERITREA' },
  { label: 'Espagne', value: 'SPAIN' },
  { label: 'Estonie', value: 'ESTONIA' },
  { label: 'Eswatini', value: 'ESWATINI' },
  { label: 'États-Unis', value: 'UNITED_STATES_OF_AMERICA' },
  { label: 'Éthiopie', value: 'ETHIOPIA' },
  { label: 'Fidji', value: 'FIJI' },
  { label: 'Finlande', value: 'FINLAND' },
  { label: 'France', value: 'FRANCE' },
  { label: 'Gabon', value: 'GABON' },
  { label: 'Gambie', value: 'GAMBIA' },
  { label: 'Géorgie', value: 'GEORGIA' },
  { label: 'Ghana', value: 'GHANA' },
  { label: 'Gibraltar', value: 'GIBRALTAR' },
  { label: 'Grèce', value: 'GREECE' },
  { label: 'Grenade', value: 'GRENADA' },
  { label: 'Groenland', value: 'GREENLAND' },
  { label: 'Guadeloupe', value: 'GUADELOUPE' },
  { label: 'Guam', value: 'GUAM' },
  { label: 'Guatemala', value: 'GUATEMALA' },
  { label: 'Guernesey', value: 'GUERNSEY' },
  { label: 'Guinée', value: 'GUINEA' },
  { label: 'Guinée-Bissau', value: 'GUINEA_BISSAU' },
  { label: 'Guinée équatoriale', value: 'EQUATORIAL_GUINEA' },
  { label: 'Guyana', value: 'GUYANA' },
  { label: 'Guyane française', value: 'FRENCH_GUIANA' },
  { label: 'Haïti', value: 'HAITI' },
  { label: 'Honduras', value: 'HONDURAS' },
  { label: 'Hong Kong', value: 'HONG_KONG' },
  { label: 'Hongrie', value: 'HUNGARY' },
  { label: 'Île Bouvet', value: 'BOUVET_ISLAND' },
  { label: 'Île de Man', value: 'ISLE_OF_MAN' },
  { label: 'Île Christmas', value: 'CHRISTMAS_ISLAND' },
  { label: 'Île Norfolk', value: 'NORFOLK_ISLAND' },
  { label: 'Îles Åland', value: 'ALAND_ISLANDS' },
  { label: 'Îles Caïmans', value: 'CAYMAN_ISLANDS' },
  { label: 'Îles Cocos', value: 'COCOS_KEELING_ISLANDS' },
  { label: 'Îles Cook', value: 'COOK_ISLANDS' },
  { label: 'Îles Féroé', value: 'FAROE_ISLANDS' },
  { label: 'Îles Malouines', value: 'FALKLAND_ISLANDS_THE_MALVINAS' },
  { label: 'Îles Mariannes du Nord', value: 'NORTHERN_MARIANA_ISLANDS' },
  { label: 'Îles Marshall', value: 'MARSHALL_ISLANDS' },
  { label: 'Îles Salomon', value: 'SOLOMON_ISLANDS' },
  { label: 'Îles Turques-et-Caïques', value: 'TURKS_AND_CAICOS_ISLANDS' },
  { label: 'Îles Vierges britanniques', value: 'VIRGIN_ISLANDS_BRITISH' },
  { label: 'Îles Vierges des États-Unis', value: 'VIRGIN_ISLANDS_US' },
  { label: 'Inde', value: 'INDIA' },
  { label: 'Indonésie', value: 'INDONESIA' },
  { label: 'Irak', value: 'IRAQ' },
  { label: 'Iran', value: 'IRAN' },
  { label: 'Irlande', value: 'IRELAND' },
  { label: 'Islande', value: 'ICELAND' },
  { label: 'Israël', value: 'ISRAEL' },
  { label: 'Italie', value: 'ITALY' },
  { label: 'Jamaïque', value: 'JAMAICA' },
  { label: 'Japon', value: 'JAPAN' },
  { label: 'Jersey', value: 'JERSEY' },
  { label: 'Jordanie', value: 'JORDAN' },
  { label: 'Kazakhstan', value: 'KAZAKHSTAN' },
  { label: 'Kenya', value: 'KENYA' },
  { label: 'Kirghizistan', value: 'KYRGYZSTAN' },
  { label: 'Kiribati', value: 'KIRIBATI' },
  { label: 'Koweït', value: 'KUWAIT' },
  { label: 'Laos', value: 'LAO_PEOPLES_DEMOCRATIC_REPUBLIC_THE' },
  { label: 'Lesotho', value: 'LESOTHO' },
  { label: 'Lettonie', value: 'LATVIA' },
  { label: 'Liban', value: 'LEBANON' },
  { label: 'Libéria', value: 'LIBERIA' },
  { label: 'Libye', value: 'LIBYA' },
  { label: 'Liechtenstein', value: 'LIECHTENSTEIN' },
  { label: 'Lituanie', value: 'LITHUANIA' },
  { label: 'Luxembourg', value: 'LUXEMBOURG' },
  { label: 'Macao', value: 'MACAO' },
  { label: 'Macédoine du Nord', value: 'NORTH_MACEDONIA' },
  { label: 'Madagascar', value: 'MADAGASCAR' },
  { label: 'Malaisie', value: 'MALAYSIA' },
  { label: 'Malawi', value: 'MALAWI' },
  { label: 'Maldives', value: 'MALDIVES' },
  { label: 'Mali', value: 'MALI' },
  { label: 'Malte', value: 'MALTA' },
  { label: 'Maroc', value: 'MOROCCO' },
  { label: 'Martinique', value: 'MARTINIQUE' },
  { label: 'Maurice', value: 'MAURITIUS' },
  { label: 'Mauritanie', value: 'MAURITANIA' },
  { label: 'Mayotte', value: 'MAYOTTE' },
  { label: 'Mexique', value: 'MEXICO' },
  { label: 'Micronésie', value: 'MICRONESIA_FEDERATED_STATES' },
  { label: 'Moldavie', value: 'MOLDOVA_THE_REPUBLIC' },
  { label: 'Monaco', value: 'MONACO' },
  { label: 'Mongolie', value: 'MONGOLIA' },
  { label: 'Monténégro', value: 'MONTENEGRO' },
  { label: 'Montserrat', value: 'MONTSERRAT' },
  { label: 'Mozambique', value: 'MOZAMBIQUE' },
  { label: 'Myanmar', value: 'MYANMAR' },
  { label: 'Namibie', value: 'NAMIBIA' },
  { label: 'Nauru', value: 'NAURU' },
  { label: 'Népal', value: 'NEPAL' },
  { label: 'Nicaragua', value: 'NICARAGUA' },
  { label: 'Niger', value: 'NIGER' },
  { label: 'Nigéria', value: 'NIGERIA' },
  { label: 'Niue', value: 'NIUE' },
  { label: 'Norvège', value: 'NORWAY' },
  { label: 'Nouvelle-Calédonie', value: 'NEW_CALEDONIA' },
  { label: 'Nouvelle-Zélande', value: 'NEW_ZEALAND' },
  { label: 'Oman', value: 'OMAN' },
  { label: 'Ouganda', value: 'UGANDA' },
  { label: 'Ouzbékistan', value: 'UZBEKISTAN' },
  { label: 'Pakistan', value: 'PAKISTAN' },
  { label: 'Palaos', value: 'PALAU' },
  { label: 'Palestine', value: 'PALESTINE_STATE' },
  { label: 'Panama', value: 'PANAMA' },
  { label: 'Papouasie-Nouvelle-Guinée', value: 'PAPUA_NEW_GUINEA' },
  { label: 'Paraguay', value: 'PARAGUAY' },
  { label: 'Pays-Bas', value: 'NETHERLANDS' },
  { label: 'Pérou', value: 'PERU' },
  { label: 'Philippines', value: 'PHILIPPINES' },
  { label: 'Pitcairn', value: 'PITCAIRN' },
  { label: 'Pologne', value: 'POLAND' },
  { label: 'Polynésie française', value: 'FRENCH_POLYNESIA' },
  { label: 'Porto Rico', value: 'PUERTO_RICO' },
  { label: 'Portugal', value: 'PORTUGAL' },
  { label: 'Qatar', value: 'QATAR' },
  { label: 'RD Congo', value: 'CONGO_THE_DEMOCRATIC_REPUBLIC_OF' },
  { label: 'République centrafricaine', value: 'CENTRAL_AFRICAN_REPUBLIC' },
  { label: 'République dominicaine', value: 'DOMINICAN_REPUBLIC' },
  { label: 'République tchèque', value: 'CZECHIA' },
  { label: 'Réunion', value: 'REUNION' },
  { label: 'Roumanie', value: 'ROMANIA' },
  { label: 'Royaume-Uni', value: 'UNITED_KINGDOM' },
  { label: 'Russie', value: 'RUSSIA' },
  { label: 'Rwanda', value: 'RWANDA' },
  { label: 'Sahara occidental', value: 'WESTERN_SAHARA' },
  { label: 'Saint-Barthélemy', value: 'SAINT_BARTHELEMY' },
  { label: 'Saint-Christophe-et-Niévès', value: 'SAINT_KITTS_AND_NEVIS' },
  { label: 'Saint-Marin', value: 'SAN_MARINO' },
  { label: 'Saint-Martin (France)', value: 'SAINT_MARTIN_FRENCH_PART' },
  { label: 'Saint-Pierre-et-Miquelon', value: 'SAINT_PIERRE_AND_MIQUELON' },
  { label: 'Saint-Vincent-et-les-Grenadines', value: 'SAINT_VINCENT_AND_THE_GRENADINES' },
  { label: 'Sainte-Hélène', value: 'SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA' },
  { label: 'Sainte-Lucie', value: 'SAINT_LUCIA' },
  { label: 'Salvador', value: 'EL_SALVADOR' },
  { label: 'Samoa', value: 'SAMOA' },
  { label: 'Samoa américaines', value: 'AMERICAN_SAMOA' },
  { label: 'Sao Tomé-et-Principe', value: 'SAO_TOME_AND_PRINCIPE' },
  { label: 'Sénégal', value: 'SENEGAL' },
  { label: 'Serbie', value: 'SERBIA' },
  { label: 'Seychelles', value: 'SEYCHELLES' },
  { label: 'Sierra Leone', value: 'SIERRA_LEONE' },
  { label: 'Singapour', value: 'SINGAPORE' },
  { label: 'Sint Maarten (Pays-Bas)', value: 'SINT_MAARTEN_DUTCH_PART' },
  { label: 'Slovaquie', value: 'SLOVAKIA' },
  { label: 'Slovénie', value: 'SLOVENIA' },
  { label: 'Somalie', value: 'SOMALIA' },
  { label: 'Soudan', value: 'SUDAN' },
  { label: 'Soudan du Sud', value: 'SOUTH_SUDAN' },
  { label: 'Sri Lanka', value: 'SRI_LANKA' },
  { label: 'Suède', value: 'SWEDEN' },
  { label: 'Suisse', value: 'SWITZERLAND' },
  { label: 'Suriname', value: 'SURINAME' },
  { label: 'Svalbard et Jan Mayen', value: 'SVALBARD_AND_JAN_MAYEN' },
  { label: 'Syrie', value: 'SYRIA' },
  { label: 'Tadjikistan', value: 'TAJIKISTAN' },
  { label: 'Taïwan', value: 'TAIWAN' },
  { label: 'Tanzanie', value: 'TANZANIA' },
  { label: 'Tchad', value: 'CHAD' },
  { label: 'Terres australes françaises', value: 'FRENCH_SOUTHERN_TERRITORIES' },
  { label: 'Territoire britannique de l\'océan Indien', value: 'BRITISH_INDIAN_OCEAN_TERRITORY_THE' },
  { label: 'Territoires mineurs éloignés des États-Unis', value: 'MINOR_OUTLYING_ISLANDS_US' },
  { label: 'Thaïlande', value: 'THAILAND' },
  { label: 'Timor oriental', value: 'TIMOR_LESTE' },
  { label: 'Togo', value: 'TOGO' },
  { label: 'Tokelau', value: 'TOKELAU' },
  { label: 'Tonga', value: 'TONGA' },
  { label: 'Trinité-et-Tobago', value: 'TRINIDAD_AND_TOBAGO' },
  { label: 'Tunisie', value: 'TUNISIA' },
  { label: 'Turkménistan', value: 'TURKMENISTAN' },
  { label: 'Turquie', value: 'TURKEY' },
  { label: 'Tuvalu', value: 'TUVALU' },
  { label: 'Ukraine', value: 'UKRAINE' },
  { label: 'Uruguay', value: 'URUGUAY' },
  { label: 'Vanuatu', value: 'VANUATU' },
  { label: 'Vatican', value: 'HOLY_SEE' },
  { label: 'Venezuela', value: 'VENEZUELA' },
  { label: 'Vietnam', value: 'VIETNAM' },
  { label: 'Wallis-et-Futuna', value: 'WALLIS_AND_FUTUNA' },
  { label: 'Yémen', value: 'YEMEN' },
  { label: 'Zambie', value: 'ZAMBIA' },
  { label: 'Zimbabwe', value: 'ZIMBABWE' },
];

/**
 * Creates dropdown options for podcast countries
 * @param {string} allLabel - Label for "All Countries" option
 * @returns {Array} Array of {label, value} objects for dropdown
 */
export function createPodcastCountryOptions(allLabel = 'Tous les pays') {
  return [
    { label: allLabel, value: '' },
    ...PODCAST_COUNTRIES
  ];
}
